---

configure_dotfiles: true
configure_homebrew: true

configure_vfox: false
configure_vscode: false

configure_docker: false
configure_jenkins: false

apt_installed_packages:
  - apt-transport-https
  - binutils
  - conntrack
  - coreutils
  - curl
  - fontconfig
  - gawk
  - gnupg2
  - unzip
  - wget
  - zsh

dnf_installed_packages:
  - epel-release
  - dnf-plugins-core
  - fontconfig
  - unzip
  - wget
  - zsh

homebrew_use_brewfile: true
homebrew_brewfile_dir: "{{ playbook_dir }}"

git_username: Jacquin Moon
git_email: jacquindev@outlook.com

dotfiles_repo: https://github.com/jacquindev/dotfiles.git
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_home: "~"

dotfiles_files:
  - .zshenv
  - .config

# REQUIRED*: change this into your shell you are using, available options: bash/zsh/fish
vfox_shell: fish

vfox_plugins:
  - name: nodejs
    versions:
      - 23.9.0  # latest available
      - 22.14.0 # LTS version
    global: 23.9.0

  - name: java
    versions:
      - 21.0.2-graalce
    global: 21.0.2-graalce

  - name: golang
    versions:
      - 1.24.1
    global: 1.24.1

vscode_extensions_install:
  - christian-kohler.path-intellisense
  - davidanson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - donjayamanne.githistory
  - dotjoshjohnson.xml
  - eamodio.gitlens
  - editorconfig.editorconfig
  - foxundermoon.shell-format
  - github.copilot
  - github.copilot-chat
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - hashicorp.terraform
  - mechatroner.rainbow-csv
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - naumovs.color-highlight
  - oderwat.indent-rainbow
  - redhat.ansible
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - samuelcolvin.jinjahtml
  - tamasfe.even-better-toml
  - timonwong.shellcheck

jenkins_plugins:
  - ansicolor
  - ant
  - antisamy-markup-formatter
  - apache-httpcomponents-client-4-api
  - blueocean
  - blueocean-dashboard
  - bootstrap5-api
  - bouncycastle-api
  - branch-api
  - build-timeout
  - caffeine-api
  - checks-api
  - cloudbees-folder
  - command-launcher
  - commons-lang3-api
  - commons-text-api
  - configuration-as-code
  - config-file-provider
  - credentials-binding
  - credentials
  - dark-theme
  - display-url-api
  - durable-task
  - echarts-api
  - favorite
  - font-awesome-api
  - git-client
  - git
  - github-api
  - github-branch-source
  - github
  - gradle
  - instance-identity
  - ionicons-api
  - jackson2-api
  - jakarta-activation-api
  - jakarta-mail-api
  - jaxb
  - jjwt-api
  - jquery3-api
  - junit
  - locale
  - lockable-resources
  - mailer
  - matrix-auth
  - matrix-project
  - metrics
  - mina-sshd-api-common
  - mina-sshd-api-core
  - okhttp-api
  - pipeline-build-step
  - pipeline-graph-analysis
  - pipeline-graph-view
  - pipeline-groovy-lib
  - pipeline-input-step
  - pipeline-milestone-step
  - pipeline-model-api
  - pipeline-model-definition
  - pipeline-model-extensions
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-tags-metadata
  - pipeline-stage-view
  - plain-credentials
  - plugin-util-api
  - resource-disposer
  - scm-api
  - script-security
  - snakeyaml-api
  - ssh-credentials
  - ssh-slaves
  - sshd
  - structs
  - timestamper
  - theme-manager
  - token-macro
  - trilead-api
  - variant
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
  - ws-cleanup
