---

- name: Setup WSL2 machine (Debian / Ubuntu / CentOS)
  hosts: all

  vars_files:
    - vars/default.config.yml
    - vars/packages.yml

  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: ansible-role-wsl2
      tags: ["wsl2", "wsl"]

    - role: ansible-role-homebrew
      when: configure_homebrew
      tags: ["homebrew"]

    - role: ansible-role-vfox
      when: configure_vfox
      tags: ["vfox"]

    - role: ansible-role-vscode
      when: configure_vscode
      tags: ["vscode", "code"]

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]

    - role: ansible-extra-packages
      when: extra_packages
      tags: ["extra", "extras"]

    - role: geerlingguy.docker
      when: configure_docker
      become: true
      tags: ["docker"]

    - role: geerlingguy.jenkins
      when: configure_jenkins
      become: true
      tags: ["jenkins"]
