---

- name: Setup homebrew_block fact
  ansible.builtin.set_fact:
    homebrew_block: "{{ homebrew_fish_block if homebrew_profile == 'fish' else homebrew_bash_block }}"

- name: Set homebrew_completion_block fact
  ansible.builtin.set_fact:
    homebrew_completion_block: "{{ homebrew_bash_completion if homebrew_profile == 'bash' else homebrew_zsh_completion if homebrew_profile == 'zsh' else homebrew_fish_completion }}"

- name: Set shell config file fact
  ansible.builtin.set_fact:
    shell_config_file: "{{ bash_config_file if homebrew_profile == 'bash' else zsh_config_file if homebrew_profile == 'zsh' else fish_config_file }}"

- name: Add Homebrew shell integration
  ansible.builtin.blockinfile:
    path: "{{ shell_config_file }}"
    block: "{{ homebrew_block }}"
    marker: "### {mark} HOMEBREW SHELL INTEGRATION BLOCK"
    mode: u+rwx
    state: present
    create: true

- name: Add Homebrew auto-completion
  ansible.builtin.blockinfile:
    path: "{{ shell_config_file }}"
    block: "{{ homebrew_completion_block }}"
    marker: "### {mark} HOMEBREW AUTO-COMPLETION BLOCK"
    mode: u+rwx
    create: true
    state: present
  when: homebrew_autocompletion
