---

- name: Install npm packages
  when: npm_packages | length > 0
  block:
    - name: Get npm command
      ansible.builtin.command: which npm
      check_mode: false
      changed_when: false
      ignore_errors: true
      register: npm_command

    - name: Install npm packages
      when: npm_command.stdout != ''
      community.general.npm:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        global: true
        executable: "{{ npm_command.stdout }}"
      loop: "{{ npm_packages }}"

- name: Install composer packages
  when: composer_packages | length > 0
  block:
    - name: Get composer command
      ansible.builtin.command: which composer
      check_mode: false
      changed_when: false
      ignore_errors: true
      register: composer_command

    - name: Install composer packages
      when: composer_command.stdout != ''
      community.general.composer:
        command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
        arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
        global_command: true
      loop: "{{ composer_packages }}"

- name: Install go packages
  when: go_packages | length > 0
  block:
    - name: Get go command
      ansible.builtin.command: which go
      check_mode: false
      changed_when: false
      ignore_errors: true
      register: go_command

    - name: Install go packages
      when: go_command.stdout != ''
      ansible.builtin.command: "{{ go_command.stdout }} install {{ item.name | default(item) }}@{{ item.version | default('latest') }}"
      loop: "{{ go_packages }}"
