---

- name: Get PHP command
  ansible.builtin.command: which php
  check_mode: false
  changed_when: false
  ignore_errors: true
  register: php_command

- name: Get composer command
  ansible.builtin.command: which composer
  check_mode: false
  changed_when: false
  ignore_errors: true
  register: composer_command

- name: Install composer packages
  community.general.composer:
    command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
    arguments: "{{ item.name | default(item) }}"
    global_command: true
    composer_executable: "{{ composer_command.stdout }}"
    php_path: "{{ php_command.stdout }}"
    ignore_platform_reqs: true
  loop: "{{ composer_packages }}"
  when:
    - php_command.stdout != ''
    - composer_command.stdout != ''
    - composer_packages | length > 0
  ignore_errors: true
