---

- name: Get npm command
  ansible.builtin.command: which npm
  check_mode: false
  changed_when: false
  ignore_errors: true
  register: npm_command

- name: Install npm packages
  community.general.npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    global: true
    executable: "{{ npm_command.stdout }}"
  with_items: "{{ npm_packages }}"
  when:
    - npm_command.stdout != ''
    - npm_packages | length > 0
