---

- name: Get pip command
  ansible.builtin.command: which pip
  check_mode: false
  changed_when: false
  ignore_errors: true
  register: pip_command

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ pip_command.stdout }}"
  with_items: "{{ pip_packages }}"
  when:
    - pip_command.stdout != ''
    - pip_packages | length > 0
