---

- name: Check if .hushlogin file exists'
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.hushlogin"
  register: hushlogin

- name: Create an empty .hushlogin file if not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: u+rwx
  when: not hushlogin.stat.exists

- name: Configure WSL using template
  ansible.builtin.template:
    src: wsl.conf.j2
    dest: /etc/wsl.conf
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Disable original resolv.conf file
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true
  when:
    - wsl_network_generate_resolve_config is defined
    - wsl_network_generate_resolve_config | bool | lower == 'false'


- name: Fix resolved network configuration
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: "nameserver 1.1.1.1"
    owner: root
    group: root
    mode: "0644"
  become: true
  when:
    - wsl_network_generate_resolve_config is defined
    - wsl_network_generate_resolve_config | bool | lower == 'false'
