---
- name: Check if .hushlogin file exists'
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.hushlogin"
  register: hushlogin

- name: Create an empty .hushlogin file if not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: u+rwx
  when: not hushlogin.stat.exists

- name: Configure WSL using template
  ansible.builtin.template:
    src: wsl.conf.j2
    dest: /etc/wsl.conf
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Check if /etc/resolv.conf is a symlink
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: symlink_check

- name: Remove origin /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  when: >
    (symlink_check.stat.islnk) and 
    (wsl_network_generate_resolve_config is defined) and 
    (wsl_network_generate_resolve_config | bool | lower == 'false')

- name: Fix resolved network configuration
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: "nameserver 1.1.1.1"
    owner: root
    group: root
    mode: "0644"
    follow: true
    backup: true
  become: true
  when: >
    (wsl_network_generate_resolve_config is defined) and
    (wsl_network_generate_resolve_config | bool | lower == 'false')

- name: Enable passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: "0644"
  become: true
