---

- name: Configure git username and email
  block:
    - name: Setup git username
      community.general.git_config:
        name: user.name
        value: "{{ git_username }}"
        scope: global
      when: git_username is defined

    - name: Setup git email
      community.general.git_config:
        name: user.email
        value: "{{ git_email }}"
        scope: global
      when: git_email is defined

- name: Setup git credential helper fact
  ansible.builtin.set_fact:
    git_credential_helper: "{{ __git_credential_helper }}"
  when: git_credential_helper is not defined

- name: Setup GCM for use with WSL
  community.general.git_config:
    name: credential.helper
    value: "{{ git_credential_helper }}"
    scope: global

- name: Ensure that .ssh directory exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "700"

- name: Generate SSH key pair for Git
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_ed25519"
    passphrase: ""
    comment: "{{ git_email }}"
    type: ed25519
    mode: "600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    force: false
  become: true
  become_user: "{{ ansible_user_id }}"
  register: ssh_key_pair

- name: Print SSH public key
  ansible.builtin.command: "cat {{ ansible_user_dir }}/.ssh/id_ed25519.pub"
  when: (ssh_key_pair.changed) or (ssh_key_pair is succeeded)
  register: ssh_pub_key_result
  become: true
  become_user: "{{ ansible_user_id }}"
