---

- name: Check if .hushlogin file exists'
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.hushlogin"
  register: hushlogin

- name: Create an empty .hushlogin file if not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: u+rwx
  when: not hushlogin.stat.exists

- name: Configure WSL using template
  ansible.builtin.template:
    src: wsl.conf.j2
    dest: /etc/wsl.conf
    mode: "0644"
    owner: root
    group: root
  become: true
