---

- name: Ensure dependencies are available
  ansible.builtin.package:
    name:
      - dnf
      - python3
      - python3-pip
      - python3-dnf
    state: present
  become: true

- name: Perform an upgrade for RedHat machine
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true

- name: Ensure packages in the list for RedHat
  ansible.builtin.dnf:
    name: "{{ dnf_installed_packages }}"
    state: present
  become: true
  when: dnf_installed_packages | length > 0

- name: Disable packages in the list for RedHat
  ansible.builtin.dnf:
    name: "{{ dnf_disabled_packages }}"
    state: absent
  become: true
  when: dnf_disabled_packages | length > 0

- name: Ensure wslu is installed (RedHat >= 8)
  become: true
  when: ansible_distribution_major_version >= "8"
  block:
    - name: Ensure pre-requisites packages
      ansible.builtin.dnf:
        name:
          - epel-release
          - dnf-plugins-core
        state: latest
        update_cache: true

    - name: Update cache
      ansible.builtin.dnf:
        update_cache: true

    - name: Enable crb repository
      community.general.dnf_config_manager:
        name: crb
        state: enabled

    - name: Enable wslutilities copr repository
      community.general.copr:
        name: wslutilities/wslu
        state: enabled

- name: Ensure wslu repository exists (RedHat <= 7)
  become: true
  when: ansible_distribution_major_version <= "7"
  block:
    - name: Add wslutilities repository for CentOS 7
      ansible.builtin.yum_repository:
        name: wslutilities
        baseurl: https://download.opensuse.org/repositories/home:/wslutilities/CentOS_7/home:wslutilities.repo
        enabled: true
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Add wslutilities repository for RHEL 7
      ansible.builtin.yum_repository:
        name: wslutilities
        baseurl: https://download.opensuse.org/repositories/home:/wslutilities/RHEL_7/home:wslutilities.repo
        enabled: true
        state: present
      when: ansible_distribution != 'CentOS'

- name: Install wslu
  ansible.builtin.dnf:
    name: wslu
    state: present
  become: true
