---

- name: Ensure dependencies are available
  ansible.builtin.package:
    name:
      - dnf
      - python3
      - python3-pip
      - python3-dnf
    state: present
  become: true

- name: Perform an upgrade for RedHat machine
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true

- name: Ensure git is installed
  ansible.builtin.dnf:
    name: git
    state: present
  become: true

- name: Ensure packages in the list for RedHat
  ansible.builtin.dnf:
    name: "{{ installed_packages }}"
    state: present
  become: true
  when: installed_packages | length > 0

- name: Disable packages in the list for RedHat
  ansible.builtin.dnf:
    name: "{{ disabled_packages }}"
    state: absent
  become: true
  when: disabled_packages | length > 0
