---

- name: Ensure XDG directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: u+rwx
  loop: "{{ xdg_skeleton_paths }}"

- name: Add XDG directories into .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: "{{ xdg_config_block }}"
    marker: "### {mark} XDG CONFIGURATION BLOCK"
    create: true
    mode: u+rwx
    state: present
  when: xdg_init_shell
