name: Lint

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 4"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install test dependencies
        run: pip install yamllint ansible ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint
